apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 834725375088.dkr.ecr.us-east-1.amazonaws.com/frontend:7.0.0
        ports:
        - containerPort: 80



--- 
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
