variable "ENV" {}
variable "COMPONENT" {}
variable "INSTANCE_TYPE" {}
variable "SPOT_INSTANCE_COUNT" {}
variable "OD_INSTANCE_COUNT" {}
variable "WORKSPATION_IP" {}
variable "PROMETHEUS_IP" {}
variable "APP_VERSION" {}
variable "APP_PORT" {}